feat: add default calendar
Kovallll/date_picker pull request #1
Opened 2024-08-28 10:04 UTC by Kovallll

2024-08-28 10:31 UTC, anyaprystavka requested changes

2024-08-28 10:31 UTC, anyaprystavka commented on .github/workflows/blank.yml
> +            - name: install modules
нужно тесты подключить

2024-08-28 10:31 UTC, anyaprystavka commented on .storybook/main.js
> - */
нужно алиасы и тут подключить

2024-08-28 10:31 UTC, anyaprystavka commented on README.md
> +-   Развернуть приложение на хостинге (heroku, vercel);
в ридми будет то
как нужно работать с библиотекой пользователю

2024-08-28 10:31 UTC, anyaprystavka commented on babel.config.cjs
файл пусто

2024-08-28 10:31 UTC, anyaprystavka commented on package.json
> +        "storybook": "^8.2.9",
тут вероятней всего нужно будет использовать peerDependencies

2024-08-28 10:31 UTC, anyaprystavka commented on vite.config.js
> +            '@': path.resolve(__dirname, 'src'),
нужно все алиасы предусмотреть
на папки

2024-08-28 10:31 UTC, anyaprystavka commented on src/components/Day/index.jsx
> +
нужно перейти на TS

2024-08-28 10:31 UTC, anyaprystavka commented on src/components/Day/index.jsx
> +    isDisabled,
не используешь ранее полученные правки по пропсам

2024-08-28 10:31 UTC, anyaprystavka commented on src/components/Day/styled.js
> +import mixins from '../../styles/mixins'
алиасы

2024-08-28 10:31 UTC, anyaprystavka commented on src/components/DaysTable/index.jsx
> +import { getCalendarDays } from '../../utils/getCalendarDays/index.js'
везде алиасы нужны

2024-08-28 10:31 UTC, anyaprystavka commented on src/components/DaysTable/index.jsx
> +    const falseArray = Array(35).fill(false)
35 - магическое число

2024-08-28 10:31 UTC, anyaprystavka commented on src/components/DaysTable/index.jsx
> +    const days = getCalendarDays(2024, monthCount)
2024 - потом значение будет динамическим?

2024-08-28 10:31 UTC, anyaprystavka commented on src/components/MonthBar/index.jsx
> +import nextIcon from '@/assets/icons/next.svg'
сделай один объект иконок

2024-08-28 10:31 UTC, anyaprystavka commented on src/components/MonthBar/styled.js
> +    width: 16px;
какие значения лежат в общей теме для стилей
обговаривался ранее в первом тестовом этот момент

2024-08-28 10:31 UTC, anyaprystavka commented on src/index.css
> +h5,
нужно использовать SC

2024-08-28 10:31 UTC, anyaprystavka commented on src/styles/theme.js
> +        sm: '6px',
значения дублируются
просто можно совместить все в один spaces
и брать значения и для ширины, отступов, высоты

2024-08-28 10:31 UTC, anyaprystavka commented on src/styles/theme.js
> +        sm: '6px',
px можно не писать
если что-то поменяется
то уже разработчик будет локально менять

2024-08-28 10:31 UTC, anyaprystavka commented on src/utils/getCalendarDays/index.js
> +        { id: 4, data: [] },
это универсальное решение?

2024-08-28 10:31 UTC, anyaprystavka commented on src/utils/getCalendarDays/index.js
> +        if (days[j].data.length === 7) {
магические числа в коде

2024-08-28 10:31 UTC, anyaprystavka commented on src/utils/getCalendarDays/index.js
> +    while (days[j].data.length !== 7) {
почему while?
лучше reduce/for

2024-08-28 10:31 UTC, anyaprystavka commented on src/components/Day/index.jsx
> +
использовать контекст для передачи size

2024-08-29 08:05 UTC, Kovallll commented on babel.config.cjs
имеешь ввиду, что babel.config.cjs пустой? странно, в нем же есть код

2024-08-29 08:05 UTC, Kovallll commented on README.md
> +-   Развернуть приложение на хостинге (heroku, vercel);
я планировал это писать в конце, когда уже создам либу, а пока что для удобства перенес туда тз

2024-08-29 08:06 UTC, Kovallll commented on .storybook/main.js
> - */
пока что с этим проблемы, не хочу тратить пока что на это все время, нужно идти дальше, а это потом пофикшу

2024-08-29 08:12 UTC, Kovallll commented on src/styles/theme.js
> +        sm: '6px',
по spaces согласен, сделал, а вот по поводу px, мне кажется что это будет труднее для разработчика исправить, ведь если писать просто числа, то в каждом файле со стилями придется писать приставку px, а если разработчик захочет перейти, допустим, на rem, то ему везде нужно это переписывать, а так в теме только поменять и готово. Если же он захочет локально в паре мест поменять, то во-первых все равно нужно придерживаться одних единиц измерения, а во-вторых если уже где-то и нужно другая единица, то можно либо написать другую, либо отнять/прибавить к значению из темы

2024-08-29 09:38 UTC, anyaprystavka commented on babel.config.cjs
чекнула
все ок

2024-08-29 09:38 UTC, anyaprystavka commented on .storybook/main.js
> - */
хорошо
под это заведена таска?

2024-08-29 09:39 UTC, anyaprystavka commented on src/styles/theme.js
> +        sm: '6px',
чаще встречала просто число

2024-08-29 09:42 UTC, Kovallll commented on .storybook/main.js
> - */
завел

2024-08-29 16:08 UTC, anyaprystavka commented on src/components/Day/index.jsx
> +    isDisabled,
деструктуризировать пропсы нужно внутри компонента, если их приходить больше 2-3ех

2024-08-29 16:33 UTC, anyaprystavka commented on src/components/DaysTable/index.tsx
> +        const activeDay = activeDays[+id - 1]
используй более явное приведение к числу
чтобы не терять  + из виду

2024-08-29 16:33 UTC, anyaprystavka commented on src/components/DaysTable/index.tsx
> +    const falseArray = Array(daysOnTable).fill(false)
значение будет пересчитываться
можно его не тут создавать
вынести в константу

2024-08-29 16:33 UTC, anyaprystavka commented on src/components/DaysTable/index.tsx
> +    console.log(days, 'days')
console.log нужно убирать

2024-08-29 16:33 UTC, anyaprystavka commented on src/constants/index.ts
> +export const daysOnTable = 35
Почему дни, если ячейки

2024-08-29 16:33 UTC, anyaprystavka commented on src/components/MonthBar/styled.ts
> +    margin: 8px 0px;
Почему не из темы?

2024-08-29 16:33 UTC, anyaprystavka commented on src/components/Day/styled.ts
> +    border-radius: ${({ isActive, isStartRange }) =>
Тема

2024-08-29 16:33 UTC, anyaprystavka commented on src/components/Day/index.jsx
> +
нет контекста
что было исправлено?

2024-08-29 16:41 UTC, anyaprystavka requested changes

2024-08-29 16:41 UTC, anyaprystavka commented on .yarn/sdks/typescript/lib/tsserver.js
> +      case `neovim`: {
зачем это тут(папка yarn)? ты указывал версию yarn в package.json

2024-08-29 16:41 UTC, anyaprystavka commented on vercel.json
> +  }
нет пустой строки в конце файла

2024-08-29 16:41 UTC, anyaprystavka commented on src/components/DefaultCalendar/index.tsx
> +    initialYear = 2024,
поставь другой год
просто через 10 лет будет 2024 дефолтным)
например 2000

2024-08-29 16:41 UTC, anyaprystavka commented on src/components/DefaultCalendar/index.tsx
> +        if (currentMonth === 12) {
магическое число

2024-08-29 16:41 UTC, anyaprystavka commented on src/components/DefaultCalendar/index.tsx
> +            setCurrentMonth(12)
магическое число

2024-08-29 16:41 UTC, anyaprystavka commented on src/components/MonthBar/index.tsx
> +    increment,
деструктуризация пропс в компоненте

2024-08-29 16:41 UTC, anyaprystavka commented on src/components/WeekBar/styled.ts
> +    ${mixins.flexRowCenter()}
нет пустой строки до миксина

2024-08-29 16:41 UTC, anyaprystavka commented on src/components/MonthBar/styled.ts
> +    margin: 8px 0px;
значение не из темы взято (spaces)

2024-08-29 16:41 UTC, anyaprystavka commented on src/components/MonthBar/styled.ts
> +    ${mixins.flexRowSB()}
нет пустой строки до и после миксина

2024-08-29 16:41 UTC, anyaprystavka commented on src/components/MonthBar/styled.ts
> +    font-weight: 700;
font-weight тоже вынеси тему и оттуда везде бери значения

2024-08-29 16:45 UTC, anyaprystavka requested changes

2024-08-29 16:45 UTC, anyaprystavka commented on .github/workflows/blank.yml
> +        branches: ['master']
последний деплой упал
потом нужно чекнуть
желательно в ближайшее время
чтобы смотреть прогресс в пр-ах

2024-08-29 16:45 UTC, anyaprystavka commented on package.json
> +        "lint:fix": "eslint --fix",
тесты в пайплайне есть
но тут в скриптах их нет
и нет никакой конфигурации в приложении

2024-08-29 19:00 UTC, Kovallll commented on package.json
> +        "lint:fix": "eslint --fix",
поправил

2024-08-29 19:15 UTC, Kovallll commented on src/components/DaysTable/index.tsx
> +        const activeDay = activeDays[+id - 1]
поправил

2024-08-29 19:15 UTC, Kovallll commented on src/components/DaysTable/index.tsx
> +    const falseArray = Array(daysOnTable).fill(false)
вынес

2024-08-29 19:16 UTC, Kovallll commented on src/components/DaysTable/index.tsx
> +    console.log(days, 'days')
ага, не заметил, убрал

2024-08-29 19:17 UTC, Kovallll commented on src/constants/index.ts
> +export const daysOnTable = 35
поправил

2024-08-29 19:27 UTC, Kovallll commented on src/components/MonthBar/styled.ts
> +    margin: 8px 0px;
поправил и тут вопрос есть, я должен каждое значение которое использую заносить в тему или если я один раз использую text-align: center, то его можно и так написать, не занося в тему?

2024-08-29 19:28 UTC, Kovallll commented on src/components/Day/styled.ts
> +    border-radius: ${({ isActive, isStartRange }) =>
поправил

2024-08-29 19:33 UTC, Kovallll commented on .yarn/sdks/typescript/lib/tsserver.js
> +      case `neovim`: {
да, её нужно удалить, а также файлы .pnp.cjs, .pnp.loader.mjs но они уже были в прошлом коммите, поэтому добавление их просто в gitignore не решит проблему и они по прежнему будут отслеживаться. Поэтому я перед коммитом хотел их удалить и при следующем коммите добавить их в игнор, но забыл)

2024-08-29 19:35 UTC, Kovallll commented on vercel.json
> +  }
поправил

2024-08-29 19:38 UTC, Kovallll commented on src/components/DefaultCalendar/index.tsx
> +        if (currentMonth === 12) {
поправил

2024-08-29 19:39 UTC, Kovallll commented on src/components/DefaultCalendar/index.tsx
> +            setCurrentMonth(12)
поправил

2024-08-29 19:39 UTC, Kovallll commented on src/components/MonthBar/styled.ts
> +    margin: 8px 0px;
поправил

2024-08-29 19:40 UTC, Kovallll commented on src/components/MonthBar/styled.ts
> +    font-weight: 700;
поправил

2024-08-29 19:40 UTC, Kovallll commented on .github/workflows/blank.yml
> +        branches: ['master']
вроде пофиксил, в следующем коммите посмотрим

2024-08-29 19:54 UTC, Kovallll commented on src/components/MonthBar/styled.ts
> +    ${mixins.flexRowSB()}
поправил

2024-08-29 19:55 UTC, Kovallll commented on src/components/WeekBar/styled.ts
> +    ${mixins.flexRowCenter()}
поправил

2024-08-29 19:55 UTC, Kovallll commented on src/components/DefaultCalendar/index.tsx
> +    initialYear = 2024,
поменял

2024-08-29 20:11 UTC, Kovallll commented on src/components/MonthBar/index.tsx
> +    increment,
не понял о чем ты, не стоит что-ли деструктуризировать?

2024-08-30 06:30 UTC, closed without merging