Feature/tests
Kovallll/date_picker pull request #10
Opened 2024-09-23 09:09 UTC by Kovallll

Добавил тесты для утилит и тесты для комопнентов. Таска: https://app.clickup.com/t/86b247n7y, Коммит: e974d7d3bec05f809bb70c9e398158c247b1bf99

2024-09-23 18:54 UTC, anyaprystavka requested changes

2024-09-23 18:54 UTC, anyaprystavka commented on src/components/Modal/config.ts
> +export const closeAltText = 'closeIcon'
пустая строка

2024-09-23 18:54 UTC, anyaprystavka commented on src/components/Cell/Cell.test.tsx
> +test('test Cell', async () => {
нейминг тест кейса не информативный

2024-09-23 18:54 UTC, anyaprystavka commented on src/components/Cell/Cell.test.tsx
> +    screen.getByText('1')
onClick можно протестировать

2024-09-23 18:54 UTC, anyaprystavka commented on src/components/DateInput/DateInput.test.tsx
> +test('test DateInput', async () => {
нейминг тест кейса

2024-09-23 18:54 UTC, anyaprystavka commented on src/components/DaysTable/DaysTable.test.tsx
> +test('test DayTable', async () => {
нейминг тест кейса

2024-09-23 18:54 UTC, anyaprystavka commented on src/components/DateInput/DateInput.test.tsx
> +                handleFocus={mockFn}
нет тест кейса на фокус, на валидацию, на изменение значения и тд

2024-09-23 18:54 UTC, anyaprystavka commented on src/components/Modal/Modal.test.tsx
> +test('test DefaultCalendar', async () => {
нейминг тест кейса

2024-09-23 18:54 UTC, anyaprystavka commented on src/components/Modal/Modal.test.tsx
> +            <Modal onCloseModal={mockFn}>
тест на click

2024-09-23 18:54 UTC, anyaprystavka commented on src/components/PopupTableCells/PopupTableCells.test.tsx
> +                activeId={1}
протестирован только рендер

2024-09-23 18:54 UTC, anyaprystavka commented on src/components/TodoModal/TodoModal.test.tsx
> +                onClose={mockFn}
протестирован только рендер

2024-09-23 18:54 UTC, anyaprystavka commented on src/components/WeekRow/WeekRow.test.tsx
> +            <WeekRow
протестирован рендер и рассмотрена один вариант работы со значением

2024-09-23 18:54 UTC, anyaprystavka commented on src/utils/getDate/getDate.test.ts
> +describe('testing utils', () => {
второй раз в нейминге testing utils
пересомтри везде нейминг тест кейсов
чтобы было более информативно что ты тестируешь

2024-09-23 18:54 UTC, anyaprystavka commented on src/components/YearCalendar/YearCalendar.test.tsx
> +test('test YearCalendar', async () => {
компонент полностью протестирован

2024-09-23 18:54 UTC, anyaprystavka commented on src/components/YearCalendar/YearCalendar.test.tsx
> +test('test YearCalendar', async () => {
нет вариативности в тесте
важно добавить в тестах вариативность

2024-09-23 18:54 UTC, anyaprystavka commented on src/components/MonthCalendar/MonthCalendar.test.tsx
> +test('test MonthCalendar', async () => {
протестирован рендер и нет вариативности

2024-09-23 18:54 UTC, anyaprystavka commented on src/components/WeekBar/WeekBar.test.tsx
> +    const sunday = screen.getByText('Su')
нет вариативности

2024-09-23 19:27 UTC, Kovallll commented on src/components/Modal/config.ts
> +export const closeAltText = 'closeIcon'
поправил

2024-09-23 20:45 UTC, Kovallll commented on src/components/Cell/Cell.test.tsx
> +test('test Cell', async () => {
поменял

2024-09-23 20:46 UTC, Kovallll commented on src/components/Cell/Cell.test.tsx
> +    screen.getByText('1')
протестировал

2024-09-23 20:47 UTC, Kovallll commented on src/components/DateInput/DateInput.test.tsx
> +test('test DateInput', async () => {
исправил

2024-09-23 20:48 UTC, Kovallll commented on src/components/DaysTable/DaysTable.test.tsx
> +test('test DayTable', async () => {
исправил

2024-09-24 05:54 UTC, Kovallll commented on src/components/DateInput/DateInput.test.tsx
> +                handleFocus={mockFn}
поправил

2024-09-24 06:10 UTC, Kovallll commented on src/components/Modal/Modal.test.tsx
> +test('test DefaultCalendar', async () => {
поправил

2024-09-24 06:10 UTC, Kovallll commented on src/components/Modal/Modal.test.tsx
> +            <Modal onCloseModal={mockFn}>
сделал

2024-09-24 06:34 UTC, Kovallll commented on src/components/MonthCalendar/MonthCalendar.test.tsx
> +test('test MonthCalendar', async () => {
поправил

2024-09-24 06:50 UTC, Kovallll commented on src/components/PopupTableCells/PopupTableCells.test.tsx
> +                activeId={1}
исправил

2024-09-24 08:17 UTC, Kovallll commented on src/components/TodoModal/TodoModal.test.tsx
> +                onClose={mockFn}
поправил

2024-09-24 08:25 UTC, Kovallll commented on src/components/WeekBar/WeekBar.test.tsx
> +    const sunday = screen.getByText('Su')
исправил

2024-09-24 09:40 UTC, Kovallll commented on src/components/WeekRow/WeekRow.test.tsx
> +            <WeekRow
изменил

2024-09-24 09:44 UTC, Kovallll commented on src/utils/getDate/getDate.test.ts
> +describe('testing utils', () => {
поправил

2024-09-24 09:44 UTC, Kovallll commented on src/components/YearCalendar/YearCalendar.test.tsx
> +test('test YearCalendar', async () => {
поправил

2024-09-24 10:01 UTC, anyaprystavka approved these changes

2024-09-24 10:09 UTC, merged