Feature/default calendar
Kovallll/date_picker pull request #2
Opened 2024-08-30 15:32 UTC by Kovallll

2024-09-02 09:13 UTC, anyaprystavka requested changes

2024-09-02 09:13 UTC, anyaprystavka commented on src/types/props/index.ts
> +export interface DefaultCalendarProps
конкретно пропсы ты можешь вынести в файл types, который будет лежать в папке компонента
где будет использоваться тип

2024-09-02 09:13 UTC, anyaprystavka commented on src/CalendarCreater/index.tsx
> +import { DefaultCalendar } from '../components/DefaultCalendar'
почему папка названа не в стиле camelCase
ты можешь конкретно этот класс вынести все же в папку service

2024-09-02 09:13 UTC, anyaprystavka commented on src/HOCs/withRange/index.tsx
> +    WrappedComponent: ComponentType<T>
подлей нужную логику

2024-09-02 09:13 UTC, anyaprystavka commented on src/components/Day/index.tsx
> +    isDisabled,
деструктуризировать пропсы нужно внутри компонента, если их приходить больше 2-3ех

2024-09-02 09:13 UTC, anyaprystavka commented on src/components/WeekBar/index.tsx
> +                <Text>{day}</Text>
нет key

2024-09-02 09:13 UTC, anyaprystavka commented on src/styles/theme.ts
> +        sm: '6px',
px в итоге не убрал
выносила ранее в парвках в пр

2024-09-02 09:13 UTC, anyaprystavka commented on .yarn/sdks/eslint/bin/eslint.js
> +#!/usr/bin/env node
зачем в итоге папка yarn в GitHub?

2024-09-02 09:13 UTC, anyaprystavka commented on .yarn/sdks/eslint/bin/eslint.js
> +#!/usr/bin/env node
нужная версия уже указана

2024-09-02 09:13 UTC, anyaprystavka commented on src/components/MonthBar/index.tsx
> +    year,
деструктуризировать пропсы нужно внутри компонента, если их приходить больше 2-3ех

2024-09-02 16:47 UTC, Kovallll commented on src/types/props/index.ts
> +export interface DefaultCalendarProps
хорошо, вынес

2024-09-02 16:48 UTC, Kovallll commented on src/CalendarCreater/index.tsx
> +import { DefaultCalendar } from '../components/DefaultCalendar'
перенес index.tsx в папку service

2024-09-02 16:51 UTC, Kovallll commented on src/components/WeekBar/index.tsx
> +                <Text>{day}</Text>
ага, уже добавил

2024-09-02 19:28 UTC, Kovallll commented on src/components/Day/index.tsx
> +    isDisabled,
сделал

2024-09-03 05:34 UTC, Kovallll commented on src/styles/theme.ts
> +        sm: '6px',
убрал

2024-09-03 05:34 UTC, Kovallll commented on src/components/MonthBar/index.tsx
> +    year,
сделал

2024-09-10 13:31 UTC, anyaprystavka approved these changes

2024-09-10 13:32 UTC, merged