Feature/range
Kovallll/date_picker pull request #3
Opened 2024-09-03 17:18 UTC by Kovallll

2024-09-04 07:49 UTC, anyaprystavka requested changes

2024-09-04 07:49 UTC, anyaprystavka commented on src/components/DaysTable/index.tsx
> +        if (!years.find((el) => el === year)) {
пересмотри использование https://react.dev/learn/you-might-not-need-an-effect

2024-09-04 07:49 UTC, anyaprystavka commented on src/components/DaysTable/index.tsx
> +            if (range.end === initialRangeEnd) {
прослеживается вложенность
что влияет на читаемость
можно ли тут избежать ее?

2024-09-04 07:49 UTC, anyaprystavka commented on src/components/DaysTable/index.tsx
> +                                    activeCellId === dayId &&
условия нагружают код
вынеси из выше отдельно

2024-09-04 07:49 UTC, anyaprystavka commented on src/components/DaysTable/index.tsx
> +                    {data.map(({ id: dayId, day }) => {
map в map
стоит вынести отрисовку мапа в компонент или в реакт-элемент

2024-09-04 07:49 UTC, anyaprystavka commented on src/utils/getCountCellsPrevYears/index.ts
> +        for (let j = 0; j < 12; j++) {
магическое число

2024-09-04 07:49 UTC, anyaprystavka commented on src/utils/getInitialCells/index.ts
> +                id: String(initialId * 12 + index + 1),
магическое число

2024-09-04 07:49 UTC, anyaprystavka commented on src/components/CalendarWithRange/index.tsx
> +
нужно добавит инпуты также для ввода даты

на инпуты нужно навесить маску(и провалидировать)

также протестировать, если пользователь вводит в первом инпуте число большее, чем во втором инпуте

2024-09-04 07:49 UTC, anyaprystavka commented on src/components/CalendarWithRange/index.tsx
> +    const calendar = new calendarCreater()
также базово нет подсветки выходных дней
их можно обозначить более серым цветом, чтобы было какое-то отличие

2024-09-04 07:49 UTC, anyaprystavka commented on src/components/CalendarWithRange/index.tsx
> +    calendar.addFeature(withRange)
также я могу при выборе диапазона кликнуть на день, который не относится к текущему месяцу
тут нужно ли не давать пользователю кликать на день или чтобы его автоматически перекидывало на следующий месяц и выбранный день

2024-09-04 07:49 UTC, anyaprystavka commented on src/utils/getCalendarCells/index.ts
> +import { getInitialCells } from '../getInitialCells'
в основном функции используются только здесь
для чего их выносить тогда по папкам?
то есть при ревью нужно перепрыгивать по ним и стараться понять что происходит
немного сложновато

организуй  структуру папок так
чтобы было удобно смотреть код

2024-09-04 07:49 UTC, anyaprystavka commented on src/styles/theme.ts
> +        endRangeBackgroundColor: '#2f80ed',
нет смены цвета в приложение - что и не требовалось
но тут цвета дублируются
для чего тогда разные переменный под низ создавать
просто можно вынести цвет один назвать его - white: '#fff' и переиспользовать
и так со всеми

2024-09-04 07:49 UTC, anyaprystavka commented on src/styles/theme.ts
> +        sm: '6',
у тебя тут могут храниться значения в spaces и ты можешь брать их и для высоты, ширины, отступов и тд

2024-09-04 07:49 UTC, anyaprystavka commented on src/constants/index.ts
> +export const initialRangeStart = -1
а что это означение? по идее же как-то с едины начинаются месяца
почему тут так?

2024-09-04 07:49 UTC, anyaprystavka commented on src/components/MonthBar/index.tsx
> +            <Image onClick={decrement} disabled={disabledPrevButton}>
нет alt

2024-09-04 07:49 UTC, anyaprystavka commented on src/components/Day/index.tsx
>  import { Container } from './styled.js'
расширение js у файла

2024-09-04 07:49 UTC, anyaprystavka commented on src/components/DaysTable/index.tsx
>  import { Container, WeekRow } from './styled.js'
расширение js у файла

2024-09-04 07:49 UTC, anyaprystavka commented on src/components/MonthBar/index.tsx
> +import { MonthBarProps } from './types'
расширение js у файла на первой строке

2024-09-04 07:49 UTC, anyaprystavka commented on src/components/WeekBar/index.tsx
>  import { Container, Text } from './styled.js'
расширение js у файла

2024-09-05 17:28 UTC, Kovallll commented on src/components/DaysTable/index.tsx
> +        if (!years.find((el) => el === year)) {
поправил

2024-09-05 17:28 UTC, Kovallll commented on src/components/DaysTable/index.tsx
> +            if (range.end === initialRangeEnd) {
поправил

2024-09-05 17:28 UTC, Kovallll commented on src/components/DaysTable/index.tsx
> +                                    activeCellId === dayId &&
поправил

2024-09-05 17:28 UTC, Kovallll commented on src/components/DaysTable/index.tsx
> +                    {data.map(({ id: dayId, day }) => {
поправил

2024-09-05 17:28 UTC, Kovallll commented on src/utils/getCountCellsPrevYears/index.ts
> +        for (let j = 0; j < 12; j++) {
поправил

2024-09-05 17:29 UTC, Kovallll commented on src/utils/getInitialCells/index.ts
> +                id: String(initialId * 12 + index + 1),
поправил

2024-09-05 17:29 UTC, Kovallll commented on src/components/CalendarWithRange/index.tsx
> +    const calendar = new calendarCreater()
поправил

2024-09-05 17:32 UTC, Kovallll commented on src/constants/index.ts
> +export const initialRangeStart = -1
это просто начальное значение, которое не должно быть от 0 и далее, ведь если задать 0, то 1 число 0 года будет уже подсвечено, как будто оно выбрано началом диапазона, поэтому решил присвоить -1. Можно было бы и null присвоить, но не хотел с этим заморачиваться, везде прописывать два типа и проверки на null

2024-09-05 17:34 UTC, Kovallll commented on src/components/MonthBar/index.tsx
> +            <Image onClick={decrement} disabled={disabledPrevButton}>
поправил

2024-09-05 17:40 UTC, Kovallll commented on src/components/Day/index.tsx
>  import { Container } from './styled.js'
убрал

2024-09-05 17:40 UTC, Kovallll commented on src/components/DaysTable/index.tsx
>  import { Container, WeekRow } from './styled.js'
убрал

2024-09-05 17:40 UTC, Kovallll commented on src/components/MonthBar/index.tsx
> +import { MonthBarProps } from './types'
убрал

2024-09-05 17:40 UTC, Kovallll commented on src/components/WeekBar/index.tsx
>  import { Container, Text } from './styled.js'
убрал

2024-09-06 06:33 UTC, Kovallll commented on src/components/CalendarWithRange/index.tsx
> +    calendar.addFeature(withRange)
сделал

2024-09-06 08:01 UTC, Kovallll commented on src/styles/theme.ts
> +        endRangeBackgroundColor: '#2f80ed',
сделал

2024-09-06 08:19 UTC, Kovallll commented on src/styles/theme.ts
> +        sm: '6',
ну все-таки, мне кажется, что не надо в spaces все подряд писать, зачем сильно раздувать всеми подряд высотами и ширинами эту переменную, лучше для высоты клетки создать cellHeight переменную, так будет понятнее что я хочу получить, а в spaces я также знаю что это значения для padding и margin, и при любом добавлении переменной в spaces я буду знать, что это значение для padding или margin. Так четче границы между этими стилями. По сути мне легче обратиться в theme, и уже взять оттуда высоту клетки(theme.cellHeight.sm) чем все писать в spaces и добавлять лишнюю вложенность (theme.spaces.cellHeight.sm). Даже если какое-то значение из spaces будет совпадать с cellHeight, то ничего страшного, зато я точно знаю, что если мне нужно только изменить высоту клетки, то я ничего больше не изменю, кроме клетки

2024-09-06 08:44 UTC, Kovallll commented on src/utils/getCalendarCells/index.ts
> +import { getInitialCells } from '../getInitialCells'
поправил

2024-09-09 07:31 UTC, anyaprystavka commented on src/styles/theme.ts
> +        sm: '6',
вот это все опиши в style guade
конкретно как в этом тестовом задании
так как тут я согласна, по-разному бывает
но в тут ест смысл

2024-09-09 08:16 UTC, anyaprystavka requested changes

2024-09-09 08:16 UTC, anyaprystavka commented on src/components/DaysTable/index.tsx
> +            handleChangeError('Первая дата не может быть больше второй!')
у тебя месяца на английском
везде используй английский

2024-09-09 08:16 UTC, anyaprystavka commented on src/components/DaysTable/index.tsx
> +        secondInputDate.length >= daysInWeek &&
это сложное условие
пересмотри везде и вынеси сложные условия выше в константу

2024-09-09 08:16 UTC, anyaprystavka commented on src/components/DaysTable/index.tsx
> +                    key={weekId}
компонент очень большой
вынеси функции по возможности отдельно

2024-09-09 08:16 UTC, anyaprystavka commented on src/components/DefaultCalendar/index.tsx
> +    const [firstInputDate, setFirstInputDateDate] = useState('')
огромное количество состояний
разбей на компоненты или вынеси логику в кастомные хуки

2024-09-09 08:16 UTC, anyaprystavka commented on src/components/DateInput/index.tsx
> +    const maskDateInput = (date: string) => {
пользователь может ввести текст в поле
нужна более строгая валидация

2024-09-09 08:16 UTC, anyaprystavka commented on src/components/DateInput/index.tsx
> +            inputYear >= 0 &&
сложные условия

2024-09-09 08:16 UTC, anyaprystavka commented on src/components/DateInput/index.tsx
> +        const clearValue = date.replace(/\//g, '')
вынеси регулярки отдельно

2024-09-09 08:16 UTC, anyaprystavka commented on src/components/DaysTable/index.tsx
> +            handleChangeError('Первая дата не может быть больше второй!')
после того как ошибка отобразилась
потом после клика на верную дату
сообщение не исчезает

2024-09-09 08:16 UTC, anyaprystavka commented on src/components/Calendar/index.tsx
> +    const calendar = new calendarCreater()
когда я переключаюсь по месяцам
прыгает верстка
когда количество строк меняется
нужна фиксированная высота

2024-09-09 08:16 UTC, anyaprystavka commented on src/decorators/withRange/index.tsx
> +        prevFirstDate?: string,
есть проверка опциональных значений?

2024-09-09 08:16 UTC, anyaprystavka commented on src/utils/getDateFormat/index.ts
> +export const getDateFormat = (
почему для каждой функции своя папка?

2024-09-09 08:16 UTC, anyaprystavka commented on src/types/index.ts
> +        md: number
файл разрастается
по семантике разбей на пару файлов
чтобы не нагромождать код

2024-09-09 08:16 UTC, anyaprystavka commented on src/components/MonthBar/stories.tsx
>          (Story) => (
подсвечивает 
что тут что-то с типизацией неверное

2024-09-09 08:16 UTC, anyaprystavka commented on src/components/WeekRow/index.tsx
> +                    +dayId > (range.start ?? +dayId) &&
используй более явное преобразование к Boolean

2024-09-09 08:16 UTC, anyaprystavka commented on src/components/Calendar/index.tsx
> +        initialMonth = defaultProps.defaultMonth,
есть проверки, что пропсы не придут?

2024-09-09 08:16 UTC, anyaprystavka commented on src/components/Calendar/index.tsx
> +        <ThemeProvider theme={theme}>
Нужен компонент, который будет служить как обертка для ThemeProvider
GlobalStyles
Context

2024-09-09 08:16 UTC, anyaprystavka commented on src/styles/theme.ts
> +        sm: '6',
вот это все опиши в style guade
конкретно как в этом тестовом задании
так как тут я согласна, по-разному бывает
но в тут ест смысл

2024-09-09 10:08 UTC, Kovallll commented on src/components/DaysTable/index.tsx
> +            handleChangeError('Первая дата не может быть больше второй!')
поправил

2024-09-09 14:09 UTC, Kovallll commented on src/components/DaysTable/index.tsx
> +        secondInputDate.length >= daysInWeek &&
поправил

2024-09-09 15:25 UTC, Kovallll commented on src/components/DaysTable/index.tsx
> +                    key={weekId}
немного сократил

2024-09-09 19:21 UTC, Kovallll commented on src/components/DateInput/index.tsx
> +    const maskDateInput = (date: string) => {
сделал

2024-09-09 19:22 UTC, Kovallll commented on src/components/DateInput/index.tsx
> +            inputYear >= 0 &&
убрал

2024-09-09 19:22 UTC, Kovallll commented on src/components/DateInput/index.tsx
> +        const clearValue = date.replace(/\//g, '')
вынес

2024-09-09 19:27 UTC, Kovallll commented on src/components/DaysTable/index.tsx
> +            handleChangeError('Первая дата не может быть больше второй!')
поправил

2024-09-09 19:34 UTC, Kovallll commented on src/components/Calendar/index.tsx
> +    const calendar = new calendarCreater()
это все дело в сторибуке, у сторях у меня стоял параметр, чтобы располагать все по центру и поэтому он сдвигался, я убрал этот параметр и теперь он прилипает к верху, как и в приложении бы прилипал и теперь верстка не едет, а строки дополнительные просто внизу появляются

2024-09-09 19:36 UTC, Kovallll commented on src/decorators/withRange/index.tsx
> +        prevFirstDate?: string,
поправил

2024-09-09 19:40 UTC, Kovallll commented on src/utils/getDateFormat/index.ts
> +export const getDateFormat = (
поправил

2024-09-09 19:42 UTC, Kovallll commented on src/types/index.ts
> +        md: number
поправил

2024-09-09 19:42 UTC, Kovallll commented on src/components/MonthBar/stories.tsx
>          (Story) => (
поправил

2024-09-09 19:42 UTC, Kovallll commented on src/components/WeekRow/index.tsx
> +                    +dayId > (range.start ?? +dayId) &&
поправил

2024-09-09 19:45 UTC, Kovallll commented on src/components/Calendar/index.tsx
> +        initialMonth = defaultProps.defaultMonth,
ну так если они не придут, то будет использоваться значение по умолчанию, только на isWithRange нет параметра по умолчанию, но он и проверяется на существование

2024-09-09 19:50 UTC, Kovallll commented on src/components/Calendar/index.tsx
> +        <ThemeProvider theme={theme}>
сделал

2024-09-09 19:50 UTC, Kovallll commented on src/components/MonthBar/stories.tsx
>          (Story) => (
поправил

2024-09-09 19:50 UTC, Kovallll commented on src/components/WeekRow/index.tsx
> +                    +dayId > (range.start ?? +dayId) &&
поправил

2024-09-09 19:50 UTC, Kovallll commented on src/components/DateInput/index.tsx
> +    const maskDateInput = (date: string) => {
сделал

2024-09-09 19:51 UTC, Kovallll commented on src/components/DaysTable/index.tsx
> +                    key={weekId}
вынес

2024-09-09 19:51 UTC, Kovallll commented on src/components/DaysTable/index.tsx
> +        secondInputDate.length >= daysInWeek &&
вынес

2024-09-09 20:12 UTC, Kovallll commented on src/components/DefaultCalendar/index.tsx
> +    const [firstInputDate, setFirstInputDateDate] = useState('')
поправил

2024-09-10 07:08 UTC, anyaprystavka requested changes

2024-09-10 07:08 UTC, anyaprystavka commented on src/components/DaysTable/index.tsx
> +                'The first date cannot be longer than the second!'
статические данные вынеси отдельно

2024-09-10 07:08 UTC, anyaprystavka commented on src/components/DaysTable/index.tsx
> +        } else if (onClickWithRange) {
вложенность затрудняет читаемость

попробуй оставить только if-ы

2024-09-10 07:08 UTC, anyaprystavka commented on src/hooks/useCurrentDate/index.ts
> +    const handleDecrementMonth = () => {
функции
который экспортируются их хука
обычно оборачиваются в useCallback

2024-09-10 10:03 UTC, Kovallll commented on src/hooks/useCurrentDate/index.ts
> +    const handleDecrementMonth = () => {
поправил

2024-09-10 10:03 UTC, Kovallll commented on src/components/DaysTable/index.tsx
> +        } else if (onClickWithRange) {
заменил

2024-09-10 10:04 UTC, Kovallll commented on src/components/DaysTable/index.tsx
> +                'The first date cannot be longer than the second!'
вынес

2024-09-10 13:13 UTC, anyaprystavka approved these changes

2024-09-10 13:14 UTC, merged