Feature/with change start day
Kovallll/date_picker pull request #4
Opened 2024-09-10 14:40 UTC by Kovallll

Перенес логику из DefaultCalendar в хок withChangeStartDay. Коммит: f7a5f25826b55b74e6512143ae4f796864942f14

2024-09-10 14:56 UTC, anyaprystavka requested changes

2024-09-10 14:56 UTC, anyaprystavka commented on src/components/DefaultCalendar/index.tsx
> +        if (isChangeStartDay) {
пересмотри использование useEffect

https://react.dev/learn/you-might-not-need-an-effect

2024-09-10 14:56 UTC, anyaprystavka commented on src/components/DefaultCalendar/index.tsx
> +    const startDay = weekDays[0] === WeekDays.Monday ? startMonday : startSunday
нужен useMemo?

2024-09-10 14:56 UTC, anyaprystavka commented on src/decorators/withChangeStartDay/index.tsx
> +        return <WrappedComponent isChangeStartDay={true} {...props} />
тут нет логики переиспользованной
просто передача props

2024-09-10 14:56 UTC, anyaprystavka commented on src/components/DefaultCalendar/index.tsx
> +    WeekDays,
почему тут с большой буквы?

2024-09-10 14:56 UTC, anyaprystavka commented on src/components/DefaultCalendar/index.tsx
> +    const [weekDays, setWeekDays] = useState(initialWeekDays)
компонент далее будет наполняться состояниями? это может быть избыточно для компонента в дальнейшем

2024-09-10 15:07 UTC, Kovallll commented on src/components/DefaultCalendar/index.tsx
> +    WeekDays,
потому что это Enum

2024-09-10 15:09 UTC, Kovallll commented on src/components/DefaultCalendar/index.tsx
> +    const [weekDays, setWeekDays] = useState(initialWeekDays)
Согласен, он и так содержит много состояний, буду по возможности этот компонент больше не нагружать, в противном же случае придется его декомпозировать или переносить логику

2024-09-10 15:12 UTC, Kovallll commented on src/components/DefaultCalendar/index.tsx
> +    const startDay = weekDays[0] === WeekDays.Monday ? startMonday : startSunday
не думаю, т.к. эта переменная не передается к memo компонент, это не сложные вычисления, которые хотелось бы кэшировать, переменная не в зависимостях, если добавить useMemo оно только хуже скажется на производительности и памяти приложения. Да и это больше не важно, т.к. я убрал это вычисление

2024-09-10 15:12 UTC, Kovallll commented on src/components/DefaultCalendar/index.tsx
> +        if (isChangeStartDay) {
поправил

2024-09-10 15:25 UTC, Kovallll commented on src/decorators/withChangeStartDay/index.tsx
> +        return <WrappedComponent isChangeStartDay={true} {...props} />
добавил

2024-09-11 06:54 UTC, anyaprystavka approved these changes

2024-09-11 07:10 UTC, merged