Feature/year&month calendars
Kovallll/date_picker pull request #5
Opened 2024-09-10 14:54 UTC by Kovallll

Добавил возможность при нажатии на месяц или год открывать специализированный календарь и переключаться в нем между годами/месяцами

2024-09-12 14:32 UTC, anyaprystavka requested changes

2024-09-12 14:32 UTC, anyaprystavka commented on src/components/Cell/styled.ts
> +        $isTwelve ? String(+theme.spaces.sm - 5) + 'px' : '0'};
используй явное преобразование

2024-09-12 14:32 UTC, anyaprystavka commented on src/components/DateBar/styled.ts
> +    ${mixins.flexRowCenter()}
пустая строка

2024-09-12 14:32 UTC, anyaprystavka commented on src/components/SwapButton/index.tsx
> +};
пустая строка

2024-09-12 14:32 UTC, anyaprystavka commented on src/components/SwapButton/styled.ts
> +export const Button = styled.button<{ disabled?: boolean }>`
inline-interface

2024-09-12 14:32 UTC, anyaprystavka commented on src/components/YearCalendar/index.tsx
> +    const initialYearData = (year: number) => {
вынеси в хелперы функцию
логика переиспользуется

2024-09-12 14:32 UTC, anyaprystavka commented on src/styles/theme.ts
> +        border: '1px solid #2f80ed',
цвет??

2024-09-12 14:32 UTC, anyaprystavka commented on src/components/TwelvePicker/index.tsx
> +const TwelvePicker = (props: TwelvePickerProps) => {
нейминг

2024-09-12 14:32 UTC, anyaprystavka commented on src/components/TwelvePicker/index.tsx
> +        dataTwelvePicker.push([
переиспользуй логику

2024-09-12 14:32 UTC, anyaprystavka commented on src/components/TwelvePicker/index.tsx
> +    const dataTwelvePicker: DataTwelvePicker[] = []
при отображении выбора года
нет границ самого календаря
<img width="363" alt="image" src="https://github.com/user-attachments/assets/93aa4cdf-476c-42ff-9dee-30036477c4e0">

2024-09-12 14:32 UTC, anyaprystavka commented on src/components/Cell/index.tsx
>          <Container
это не контейнер

2024-09-12 14:32 UTC, anyaprystavka commented on src/components/Cell/styled.ts
> +        $isTwelve ? String(+theme.spaces.sm - 5) + 'px' : '0'};
так везде String используется???

не нужно отнимать значения
можно запутаться
оставляй как есть

2024-09-12 14:32 UTC, anyaprystavka commented on src/components/Cell/types.ts
> +    DayProps,
Omit использовать не очень хорошая идея

так как есть в DayProps что-то поменяется
то тип можно и не найти

2024-09-12 14:43 UTC, Kovallll commented on src/components/Cell/styled.ts
> +        $isTwelve ? String(+theme.spaces.sm - 5) + 'px' : '0'};
хорошо, я просто в тему добавил новое значение и его использовал

2024-09-12 14:43 UTC, Kovallll commented on src/components/DateBar/styled.ts
> +    ${mixins.flexRowCenter()}
исправил

2024-09-12 14:43 UTC, Kovallll commented on src/components/SwapButton/index.tsx
> +};
исправил

2024-09-12 14:45 UTC, Kovallll commented on src/components/SwapButton/styled.ts
> +export const Button = styled.button<{ disabled?: boolean }>`
исправил

2024-09-13 06:09 UTC, Kovallll commented on src/components/TwelvePicker/index.tsx
> +const TwelvePicker = (props: TwelvePickerProps) => {
поправил

2024-09-13 06:46 UTC, anyaprystavka requested changes

2024-09-13 06:46 UTC, anyaprystavka commented on src/components/Calendar/index.tsx
> +export const DateContext = createContext({
выносим контекст в отдельную папку context в src

2024-09-13 06:46 UTC, anyaprystavka commented on src/components/Calendar/index.tsx
> +        console.log(year)
console.log-и

2024-09-13 06:46 UTC, anyaprystavka commented on src/components/Cell/styled.ts
> +        $isActive,
дублирование
тут можно один раз достать значения и использовать во везде в Container

2024-09-13 06:46 UTC, anyaprystavka commented on src/components/Cell/styled.ts
> +        $isActive,
посомтри как через css делать

2024-09-13 06:46 UTC, anyaprystavka commented on src/components/DateBar/index.tsx
> +                <img src={prevIcon} aria-hidden="true" alt={prevImageAlt} />
styled-components

2024-09-13 06:46 UTC, anyaprystavka commented on src/components/DateBar/index.tsx
> +                <img src={nextIcon} aria-hidden="true" alt={nextImageAlt} />
styled-components

2024-09-13 06:46 UTC, anyaprystavka commented on src/components/TwelvePicker/index.tsx
> +const TwelveTable = (props: TwelveTableProps) => {
тут лучше добавить
так как таблица подразумевает непросто отображение ячеек

нейминг плохой
у тебя тут таблица лет

2024-09-13 06:46 UTC, anyaprystavka commented on src/components/WeekCalendar/index.tsx
> +    const countWeeks = 52
вынеси константы из файла

2024-09-13 06:46 UTC, anyaprystavka commented on src/components/WeekCalendar/styled.ts
> +export const Container = styled.section`
Почему это Container? Тут секция

2024-09-13 06:46 UTC, anyaprystavka commented on src/components/WeekCalendar/styled.ts
> +export const Buttons = styled.div`
div - Buttons????

2024-09-13 06:46 UTC, anyaprystavka commented on src/components/WeekRow/index.tsx
> +    const cellsInMonth = getCellsInMonth(year, currentMonth - 1)
каждый раз происходит пересчет при ререндере компонента

2024-09-13 06:46 UTC, anyaprystavka commented on src/components/YearCalendar/styled.ts
> +export const Buttons = styled.div`
Buttons????

2024-09-13 06:46 UTC, anyaprystavka commented on src/components/YearCalendar/styled.ts
> +export const Container = styled.section`
Container??

2024-09-13 06:46 UTC, anyaprystavka commented on src/styles/mixins.ts
> +        if (inRange || isActive || isEndRange || isStartRange)
константа

2024-09-13 06:46 UTC, anyaprystavka commented on src/styles/theme.ts
> +        selectedWeekColor: '#c2eceb	',
форматирование

2024-09-13 06:46 UTC, anyaprystavka commented on src/types/theme.ts
> +    twelveStyles: {
twelve убираем везде по неймингу

2024-09-13 06:46 UTC, anyaprystavka commented on src/utils/getCells/index.ts
> +const getInitialCells = (len: number) => {
вот эту логику нужно переиспользовать

2024-09-13 14:15 UTC, Kovallll commented on src/components/YearCalendar/index.tsx
> +    const initialYearData = (year: number) => {
поправил

2024-09-13 14:21 UTC, Kovallll commented on src/styles/theme.ts
> +        border: '1px solid #2f80ed',
поправил

2024-09-13 14:21 UTC, Kovallll commented on src/components/TwelvePicker/index.tsx
> +const TwelvePicker = (props: TwelvePickerProps) => {
поправил

2024-09-13 14:49 UTC, Kovallll commented on src/components/TwelvePicker/index.tsx
> +        dataTwelvePicker.push([
сделал

2024-09-13 15:13 UTC, Kovallll commented on src/components/TwelvePicker/index.tsx
> +    const dataTwelvePicker: DataTwelvePicker[] = []
поправил

2024-09-13 15:15 UTC, Kovallll commented on src/components/Cell/index.tsx
>          <Container
поправил

2024-09-13 15:48 UTC, Kovallll commented on src/components/Calendar/index.tsx
> +export const DateContext = createContext({
поправил

2024-09-13 16:23 UTC, Kovallll commented on src/components/Cell/styled.ts
> +        $isActive,
исправил

2024-09-13 16:27 UTC, Kovallll commented on src/utils/getCells/index.ts
> +const getInitialCells = (len: number) => {
поправил

2024-09-13 16:39 UTC, Kovallll commented on src/types/theme.ts
> +    twelveStyles: {
убрал

2024-09-13 16:40 UTC, Kovallll commented on src/styles/theme.ts
> +        selectedWeekColor: '#c2eceb	',
поправил

2024-09-13 17:47 UTC, Kovallll commented on src/styles/mixins.ts
> +        if (inRange || isActive || isEndRange || isStartRange)
добавил

2024-09-13 17:51 UTC, Kovallll commented on src/components/YearCalendar/styled.ts
> +export const Container = styled.section`
изменил

2024-09-13 17:51 UTC, Kovallll commented on src/components/YearCalendar/styled.ts
> +export const Buttons = styled.div`
изменил

2024-09-13 17:51 UTC, Kovallll commented on src/components/WeekCalendar/styled.ts
> +export const Buttons = styled.div`
изменил

2024-09-13 17:51 UTC, Kovallll commented on src/components/WeekCalendar/styled.ts
> +export const Container = styled.section`
изменил

2024-09-13 17:58 UTC, Kovallll commented on src/components/WeekRow/index.tsx
> +    const cellsInMonth = getCellsInMonth(year, currentMonth - 1)
поправил

2024-09-13 18:04 UTC, Kovallll commented on src/components/WeekCalendar/index.tsx
> +    const countWeeks = 52
поправил

2024-09-13 18:05 UTC, Kovallll commented on src/components/TwelvePicker/index.tsx
> +const TwelveTable = (props: TwelveTableProps) => {
поправил

2024-09-13 18:09 UTC, Kovallll commented on src/components/DateBar/index.tsx
> +                <img src={prevIcon} aria-hidden="true" alt={prevImageAlt} />
поправил

2024-09-13 18:09 UTC, Kovallll commented on src/components/DateBar/index.tsx
> +                <img src={nextIcon} aria-hidden="true" alt={nextImageAlt} />
поправил

2024-09-13 18:09 UTC, Kovallll commented on src/components/Cell/types.ts
> +    DayProps,
поправил

2024-09-13 18:20 UTC, Kovallll commented on src/components/Calendar/index.tsx
> +        console.log(year)
убрал

2024-09-15 08:00 UTC, anyaprystavka commented on src/components/Calendar/index.tsx
> +import { DateProvider } from '@providers/DateProvider'
если тут указана текущая неделя
то когда начинается она с воскресенья
то выделяется неделя другая
которая не содержит 15 число(текущий день)
<img width="283" alt="image" src="https://github.com/user-attachments/assets/20c55814-fabf-4f87-b264-893908491f32">

2024-09-15 08:00 UTC, anyaprystavka commented on src/components/Cell/styled.ts
> +export const CellItem = styled.button<CellItemProps>`
это кнопка - содержимое ячейки

2024-09-15 08:00 UTC, anyaprystavka commented on src/components/WeekCalendar/styled.ts
> +export const Container = styled.section`
секция чего??

2024-09-15 09:19 UTC, Kovallll commented on src/components/Calendar/index.tsx
> +import { DateProvider } from '@providers/DateProvider'
исправил

2024-09-15 09:25 UTC, Kovallll commented on src/components/Cell/styled.ts
> +export const CellItem = styled.button<CellItemProps>`
изменил

2024-09-16 05:29 UTC, anyaprystavka approved these changes

2024-09-16 06:33 UTC, merged