Feature/holidays
Kovallll/date_picker pull request #7
Opened 2024-09-16 14:59 UTC by Kovallll

Реализовал возможность добавления праздничных дней,выделение стандартных праздников.Таска:https://app.clickup.com/t/86b1rkbnq,  Коммит: 2ee95b13a3515c097672174e08e68af8f9c71f17

2024-09-16 18:27 UTC, anyaprystavka requested changes

2024-09-16 18:27 UTC, anyaprystavka commented on src/components/Cell/styled.ts
> +export const Wrap = styled.div``
для чего он тут?

2024-09-16 18:27 UTC, anyaprystavka commented on src/components/Cell/styled.ts
> +    ${mixins.flexRowCenter}
после миксина строка

2024-09-16 18:27 UTC, anyaprystavka commented on src/components/WeekRow/index.tsx
> +                const holidayItem = holidaysDates.find((item) => {
пересчет

2024-09-16 18:27 UTC, anyaprystavka commented on src/components/WeekRow/index.tsx
> +                    if (isEveryYearHoliday) {
очень громоздко все

2024-09-16 18:27 UTC, anyaprystavka commented on src/constants/index.ts
> +    {
громоздкий файл

2024-09-16 18:27 UTC, anyaprystavka commented on src/providers/HolidaysProvider/index.tsx
> +    const generalHolidays = getHolidaysData(holidays)
не плоди контексты
нагружаешь приложение
(этот оставляй)

2024-09-16 18:27 UTC, anyaprystavka commented on src/components/Cell/stories.tsx
> +}
пустая строка

2024-09-16 18:27 UTC, anyaprystavka commented on src/components/Cell/styled.ts
> +export const Wrap = styled.div``
пустой тег?

2024-09-16 18:27 UTC, anyaprystavka commented on src/components/Cell/index.tsx
> +    if ((holiday?.length ?? 0) >= maxLenHolidayText) {
почему не в декораторе?

2024-09-16 18:31 UTC, Kovallll commented on src/components/Cell/styled.ts
> +export const Wrap = styled.div``
убрал

2024-09-16 18:33 UTC, Kovallll commented on src/components/Cell/styled.ts
> +    ${mixins.flexRowCenter}
добавил

2024-09-16 19:21 UTC, Kovallll commented on src/components/WeekRow/index.tsx
> +                const holidayItem = holidaysDates.find((item) => {
вынес в декоратор

2024-09-16 19:22 UTC, Kovallll commented on src/components/WeekRow/index.tsx
> +                    if (isEveryYearHoliday) {
убрал часть с праздниками, стало меньше

2024-09-17 05:35 UTC, Kovallll commented on src/components/Cell/stories.tsx
> +}
добавил

2024-09-17 05:36 UTC, Kovallll commented on src/components/Cell/index.tsx
> +    if ((holiday?.length ?? 0) >= maxLenHolidayText) {
переместил в декоратор

2024-09-17 05:39 UTC, Kovallll commented on src/providers/HolidaysProvider/index.tsx
> +    const generalHolidays = getHolidaysData(holidays)
Ну я решил, раз в тестовом написано использовать декораторы, а у меня тут получается и декоратор(тут логика по выявлению праздничного дня) и контекст(тут получение массива всех праздников), тогда я использую лучше декоратор. Хотя контекст лучше бы смотрелся, т.к. не создает дриллинга, но опять же слишком много получается контекстов и в таком случае в реальном проекте я бы использовал стейт менеджер, чтобы избавиться от двух проблем сразу

2024-09-17 05:44 UTC, Kovallll commented on src/constants/index.ts
> +    {
уменьшил

2024-09-17 07:48 UTC, anyaprystavka requested changes

2024-09-17 07:48 UTC, anyaprystavka commented on src/decorators/withHolidays/index.tsx
> +    { date: '15/03/*', holiday: 'Constitution Day' },
статику все-таки вынести отдельно

2024-09-17 07:48 UTC, anyaprystavka commented on src/providers/HolidaysProvider/index.tsx
> +    const generalHolidays = getHolidaysData(holidays)
хорошо
тогда в дальнейшем предусмотри этот вопрос

2024-09-17 11:13 UTC, Kovallll commented on src/decorators/withHolidays/index.tsx
> +    { date: '15/03/*', holiday: 'Constitution Day' },
вынес

2024-09-17 11:16 UTC, anyaprystavka approved these changes

2024-09-18 12:39 UTC, anyaprystavka approved these changes

2024-09-18 13:18 UTC, merged