Feature/todos
Kovallll/date_picker pull request #9
Opened 2024-09-19 18:09 UTC by Kovallll

Добавил возможность добавления todo на определенную дату в календаре. Таска: https://app.clickup.com/t/86b1rk8yx, Коммит: 42e04b14e3519eebbe2b0aa1a4cc00e33894f7bc

2024-09-20 10:52 UTC, anyaprystavka requested changes

2024-09-20 10:52 UTC, anyaprystavka commented on src/components/Calendar/index.tsx
> +    if (isWithTodos) {
попробуй заюзать свою библиотеку в приложени
если окно по добавлению задач будет появляться так справа и закрывать что-то другое - стоит подправить чтобы возможно добавления задач происходила в самом календаре
то есть вместо сетки, чтобы отображался ui по добавлению задач

кнопка "Remove all" избыточна, так как задач не т никаких
<img width="893" alt="image" src="https://github.com/user-attachments/assets/b598667e-8625-490c-b956-988d66a6862f">

2024-09-20 10:52 UTC, anyaprystavka commented on src/components/Calendar/index.tsx
> +        calendar.addFeature(withTodos)
ввела название задачи, добавила в спискок,  потом удалила
и название осталось в input
<img width="576" alt="image" src="https://github.com/user-attachments/assets/4d1ac4c1-fe51-4114-a101-69d2cde3a20a">

2024-09-20 10:52 UTC, anyaprystavka commented on src/components/Calendar/index.tsx
> +    }
уже после добавления задач
вижу, что отображается ячейка дня иначе
давай понять, что тут есть задачи

но как их посмотреть теперь???
<img width="903" alt="image" src="https://github.com/user-attachments/assets/3cf316b7-a3f3-4dca-ba3f-3c2ff692bca8">

2024-09-20 10:52 UTC, anyaprystavka commented on src/components/Cell/styled.ts
> +export const TodoCircle = styled.div`
поменяй нейминг

2024-09-20 10:52 UTC, anyaprystavka commented on src/components/DefaultCalendar/index.tsx
> +    const todo = localStorage
useMemo?

2024-09-20 10:52 UTC, anyaprystavka commented on src/components/TodoModal/index.tsx
> +    addTodo,
memo?

2024-09-20 10:52 UTC, anyaprystavka commented on src/components/DefaultCalendar/index.tsx
> +                        addTodo={handleAddTodo}
оптимизация?

2024-09-20 10:52 UTC, anyaprystavka commented on src/components/DefaultCalendar/styled.ts
> +        const border = mixins.elementBorder(
в приложении другие кнопки
если есть у них общие стили, стоит вынести их отдельно и наследоваться
export const TodoButton = styled(DefaultButton)``

2024-09-20 10:52 UTC, anyaprystavka commented on src/components/DefaultCalendar/types.ts
> +    handleRemoveAllTodos?: (cellId: string) => Todo[]
есть проверка на опциональный параметр??

2024-09-20 10:52 UTC, anyaprystavka commented on src/components/Modal/index.tsx
> +            <Window ref={modalRef}>
почему Window?

2024-09-20 10:52 UTC, anyaprystavka commented on src/components/TodoModal/index.tsx
> +                    <Todo>
key

2024-09-20 10:52 UTC, anyaprystavka commented on src/components/TodoModal/index.tsx
> +                createPortal(
несколько раз используется createPortal
стоит переиспользовать логику

2024-09-20 13:43 UTC, Kovallll commented on src/components/Calendar/index.tsx
> +    if (isWithTodos) {
исправил, добавил модалку поверх дней. Кнопка Remove all изначально задизейблена ,как и add, но при вводе в инпут add становится активной, а remove all становится активной когда хотя бы один элемент появляется в списке

2024-09-20 13:44 UTC, Kovallll commented on src/components/Calendar/index.tsx
> +        calendar.addFeature(withTodos)
исправил, очищаю инпут после добавления задачи в список

2024-09-20 13:54 UTC, Kovallll commented on src/components/Cell/styled.ts
> +export const TodoCircle = styled.div`
изменил

2024-09-20 13:59 UTC, Kovallll commented on src/components/TodoModal/index.tsx
> +    addTodo,
добавил

2024-09-20 13:59 UTC, Kovallll commented on src/components/DefaultCalendar/index.tsx
> +    const todo = localStorage
добавил

2024-09-20 14:00 UTC, Kovallll commented on src/components/DefaultCalendar/index.tsx
> +                        addTodo={handleAddTodo}
добавил memo

2024-09-20 14:38 UTC, Kovallll commented on src/components/DefaultCalendar/styled.ts
> +        const border = mixins.elementBorder(
исправил

2024-09-20 14:38 UTC, Kovallll commented on src/components/DefaultCalendar/types.ts
> +    handleRemoveAllTodos?: (cellId: string) => Todo[]
есть, в DefaultCalendar в isTodos

2024-09-20 14:40 UTC, Kovallll commented on src/components/Modal/index.tsx
> +            <Window ref={modalRef}>
ну это модальное окно, вот этот блок содержит основной контент окна, поэтому назвал Window

2024-09-20 14:41 UTC, Kovallll commented on src/components/TodoModal/index.tsx
> +                    <Todo>
исправил

2024-09-20 14:45 UTC, Kovallll commented on src/components/TodoModal/index.tsx
> +                createPortal(
исправил

2024-09-23 07:20 UTC, anyaprystavka commented on src/components/Calendar/index.tsx
> +    if (isWithTodos) {
нет ограничения на ввод данных в задаче - сделай ограничение по длине

2024-09-23 07:41 UTC, Kovallll commented on src/components/Calendar/index.tsx
> +    if (isWithTodos) {
исправил

2024-09-23 07:42 UTC, anyaprystavka approved these changes

2024-09-23 07:42 UTC, merged